### ISSUE TITLE
Misplaced highlighting

### ISSUE THREAD

**Issue by arlelommel** [multidimensionalquality/qt21-scorecard#39]
When you leave a project and come back to it, previously applied highlighting in the target is displayed in the source and cannot be deleted.

In the example shown, "two day" in the target had been highlighted. I left the project and came back and now it is displayed in the geometrically appropriate position within the source segment. It cannot be edited or deleted.

![misplacedhighlighting](https://cloud.githubusercontent.com/assets/6010954/11077590/e6ba4bee-87ce-11e5-8605-94aa3f14336d.png)

**Comment by jnehring** [comment]
@arlelommel wrote

The highlighting problem should be a very quick fix. The highlights are stored separately from the text, in a format like this:

sc.highlight.setHighlights( "29670", "\x22,\x22\u00FAltima\x20instancia\x22,\x220\x3A1\x22,63,16\x5D,\x22,\x22derecho\x22,\x220\x3A3\x22,54,7\x5D\x5D", "source" );

The problem is that the last parameter (source vs. target) has somehow been switched, and when it says source it should say target and when it says target it should say source.

**Comment by jnehring** [comment]
fixed. the bugfix is installed  in the live version

**Comment by arlelommel** [comment]
Thanks, Jan. This indeed completely fixes the problem :-)

-Arle
